### ISSUE TITLE
What is the blueprints?

### ISSUE THREAD

**Issue by jeniaefimov** [FerrariHD/Tank-Biathlon#1]
Can you explain me what is the blueprints technology? I try to use google to understand what is it, but without real understanding. And another one you write that user should only click to the menu item, I can't use the keyboard for choose menu item? At all I think it's great idea, create this game. Good luck?

**Comment by FerrariHD** [comment]
Blueprints - https://docs.unrealengine.com/latest/INT/Engine/Blueprints/
Да, на данном этапе нет планов на реализацию возможности выбора пунктов меню с помощью клавиатуры. Возможно данная возможность появится в будущем. Следите за новостями.
